// Code generated by protoc-gen-go. DO NOT EDIT.
// source: HerdiusEngineeringTask/proto/findMax.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindMaximumNumRequest struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Codestr              string   `protobuf:"bytes,2,opt,name=codestr,proto3" json:"codestr,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Clientpubkey         string   `protobuf:"bytes,4,opt,name=clientpubkey,proto3" json:"clientpubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaximumNumRequest) Reset()         { *m = FindMaximumNumRequest{} }
func (m *FindMaximumNumRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaximumNumRequest) ProtoMessage()    {}
func (*FindMaximumNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8286ec40352d96b4, []int{0}
}

func (m *FindMaximumNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaximumNumRequest.Unmarshal(m, b)
}
func (m *FindMaximumNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaximumNumRequest.Marshal(b, m, deterministic)
}
func (m *FindMaximumNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaximumNumRequest.Merge(m, src)
}
func (m *FindMaximumNumRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaximumNumRequest.Size(m)
}
func (m *FindMaximumNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaximumNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaximumNumRequest proto.InternalMessageInfo

func (m *FindMaximumNumRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *FindMaximumNumRequest) GetCodestr() string {
	if m != nil {
		return m.Codestr
	}
	return ""
}

func (m *FindMaximumNumRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *FindMaximumNumRequest) GetClientpubkey() string {
	if m != nil {
		return m.Clientpubkey
	}
	return ""
}

type FindMaximumNumResponse struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaximumNumResponse) Reset()         { *m = FindMaximumNumResponse{} }
func (m *FindMaximumNumResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaximumNumResponse) ProtoMessage()    {}
func (*FindMaximumNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8286ec40352d96b4, []int{1}
}

func (m *FindMaximumNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaximumNumResponse.Unmarshal(m, b)
}
func (m *FindMaximumNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaximumNumResponse.Marshal(b, m, deterministic)
}
func (m *FindMaximumNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaximumNumResponse.Merge(m, src)
}
func (m *FindMaximumNumResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaximumNumResponse.Size(m)
}
func (m *FindMaximumNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaximumNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaximumNumResponse proto.InternalMessageInfo

func (m *FindMaximumNumResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*FindMaximumNumRequest)(nil), "proto.FindMaximumNumRequest")
	proto.RegisterType((*FindMaximumNumResponse)(nil), "proto.FindMaximumNumResponse")
}

func init() {
	proto.RegisterFile("HerdiusEngineeringTask/proto/findMax.proto", fileDescriptor_8286ec40352d96b4)
}

var fileDescriptor_8286ec40352d96b4 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xf2, 0x48, 0x2d, 0x4a,
	0xc9, 0x2c, 0x2d, 0x76, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0x4d, 0x2d, 0xca, 0xcc, 0x4b, 0x0f, 0x49,
	0x2c, 0xce, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xcb, 0xcc, 0x4b, 0xf1, 0x4d, 0xac,
	0xd0, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94, 0x52, 0x2b, 0x23, 0x97, 0xa8, 0x1b, 0x44, 0x22, 0x33,
	0xb7, 0x34, 0xd7, 0xaf, 0x34, 0x37, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x80, 0x8b,
	0x39, 0xaf, 0x34, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc4, 0x14, 0x92, 0xe0, 0x62,
	0x4f, 0xce, 0x4f, 0x49, 0x2d, 0x2e, 0x29, 0x92, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x85, 0x64, 0xb8, 0x38, 0x8b, 0x33, 0xd3, 0xf3, 0x12, 0x4b, 0x4a, 0x8b, 0x52, 0x25, 0x98, 0x15,
	0x18, 0x35, 0x78, 0x82, 0x10, 0x02, 0x42, 0x4a, 0x5c, 0x3c, 0xc9, 0x39, 0x99, 0xa9, 0x79, 0x25,
	0x05, 0xa5, 0x49, 0xd9, 0xa9, 0x95, 0x12, 0x2c, 0x60, 0xcd, 0x28, 0x62, 0x4a, 0x5a, 0x5c, 0x62,
	0xe8, 0xce, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x74, 0x87, 0x51, 0x06, 0x97, 0x20, 0x54,
	0xad, 0x5f, 0x69, 0x6e, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x30, 0x17, 0x1f, 0xaa,
	0x01, 0x42, 0x32, 0x10, 0x9f, 0xea, 0x61, 0xf5, 0x9e, 0x94, 0x2c, 0x0e, 0x59, 0x88, 0xad, 0x4a,
	0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x4e, 0xec, 0x51, 0x90, 0x60, 0x4a, 0x62, 0x03, 0x53, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xa1, 0x82, 0x1e, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FindMaxNumServiceClient is the client API for FindMaxNumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindMaxNumServiceClient interface {
	FindMaximumNum(ctx context.Context, opts ...grpc.CallOption) (FindMaxNumService_FindMaximumNumClient, error)
}

type findMaxNumServiceClient struct {
	cc *grpc.ClientConn
}

func NewFindMaxNumServiceClient(cc *grpc.ClientConn) FindMaxNumServiceClient {
	return &findMaxNumServiceClient{cc}
}

func (c *findMaxNumServiceClient) FindMaximumNum(ctx context.Context, opts ...grpc.CallOption) (FindMaxNumService_FindMaximumNumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FindMaxNumService_serviceDesc.Streams[0], "/proto.FindMaxNumService/FindMaximumNum", opts...)
	if err != nil {
		return nil, err
	}
	x := &findMaxNumServiceFindMaximumNumClient{stream}
	return x, nil
}

type FindMaxNumService_FindMaximumNumClient interface {
	Send(*FindMaximumNumRequest) error
	Recv() (*FindMaximumNumResponse, error)
	grpc.ClientStream
}

type findMaxNumServiceFindMaximumNumClient struct {
	grpc.ClientStream
}

func (x *findMaxNumServiceFindMaximumNumClient) Send(m *FindMaximumNumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *findMaxNumServiceFindMaximumNumClient) Recv() (*FindMaximumNumResponse, error) {
	m := new(FindMaximumNumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FindMaxNumServiceServer is the server API for FindMaxNumService service.
type FindMaxNumServiceServer interface {
	FindMaximumNum(FindMaxNumService_FindMaximumNumServer) error
}

// UnimplementedFindMaxNumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFindMaxNumServiceServer struct {
}

func (*UnimplementedFindMaxNumServiceServer) FindMaximumNum(srv FindMaxNumService_FindMaximumNumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximumNum not implemented")
}

func RegisterFindMaxNumServiceServer(s *grpc.Server, srv FindMaxNumServiceServer) {
	s.RegisterService(&_FindMaxNumService_serviceDesc, srv)
}

func _FindMaxNumService_FindMaximumNum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FindMaxNumServiceServer).FindMaximumNum(&findMaxNumServiceFindMaximumNumServer{stream})
}

type FindMaxNumService_FindMaximumNumServer interface {
	Send(*FindMaximumNumResponse) error
	Recv() (*FindMaximumNumRequest, error)
	grpc.ServerStream
}

type findMaxNumServiceFindMaximumNumServer struct {
	grpc.ServerStream
}

func (x *findMaxNumServiceFindMaximumNumServer) Send(m *FindMaximumNumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *findMaxNumServiceFindMaximumNumServer) Recv() (*FindMaximumNumRequest, error) {
	m := new(FindMaximumNumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FindMaxNumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FindMaxNumService",
	HandlerType: (*FindMaxNumServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMaximumNum",
			Handler:       _FindMaxNumService_FindMaximumNum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "HerdiusEngineeringTask/proto/findMax.proto",
}
